Spending/Models/CategoryGroup.cs
using System;
using System.Collections.Generic;

namespace Spending.Models
{
	public class CategoryGroup
	{
		public CategoryGroup()
		{
			this.Categories = new List<Category>();
		}

		public int Id { get; set; }
		public string Name { get; set; }
		public int Order { get; set; }

		public virtual ICollection<Category> Categories { get; set; }
	}
}

Spending/Controllers/CategoryGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spending.Models;

namespace Spending.Controllers
{
	public class CategoryGroupsController : Controller
	{
		private SpendingContext db = new SpendingContext();

		[HttpPost]
		public ActionResult UpdateOrder(int id, int order)
		{
			var group = db.CategoryGroups.Find(id);

			if (group == null)
			{
				return HttpNotFound();
			}

			group.Order = order;

			db.CategoryGroups.Attach(group);

			var categoryEntry = db.Entry(group);
			categoryEntry.Property(x => x.Order).IsModified = true;

			byte currOrder = 0;

			foreach (var item in db.CategoryGroups.OrderBy(x => x.Order))
			{
				if (currOrder == order)
				{
					currOrder++;
				}

				if (item != group)
				{
					item.Order = currOrder++;
				}
			}

			db.SaveChanges();

			return new EmptyResult();
		}

		public ActionResult Create()
		{
            return View(new CategoryGroup());
		}

		[HttpPost]
		public ActionResult Create(CategoryGroup group)
		{
			if (ModelState.IsValid)
			{
				db.CategoryGroups.Add(group);
	
				byte order = 0;

				foreach (var item in db.CategoryGroups.OrderBy(x => x.Order))
				{
					if (order == group.Order)
					{
						order++;
					}

					if (item != group)
					{
						item.Order = order++;
					}
				}

				db.SaveChanges();

                return RedirectToAction("Index", "Home");
			}

			return View(group);
		}

		public ActionResult Edit(int id = 0)
		{
			CategoryGroup group = db.CategoryGroups.Find(id);

			if (group == null)
			{
				return HttpNotFound();
			}

			return View(group);
		}

		[HttpPost]
		public ActionResult Edit(CategoryGroup group)
		{
			if (ModelState.IsValid)
			{
				db.CategoryGroups.Attach(group);
				var entry = db.Entry(group);
				entry.Property(x => x.Name).IsModified = true;
				entry.Property(x => x.Order).IsModified = true;

				byte order = 0;

				foreach (var item in db.CategoryGroups.OrderBy(x => x.Order))
				{
					if (order == group.Order)
					{
						order++;
					}

					if (item != group)
					{
						item.Order = order++;
					}
				}

				db.SaveChanges();

				return RedirectToAction("Index", "Home");
			}

			return View(group);
		}

		public ActionResult Delete(int id = 0)
		{
			CategoryGroup group = db.CategoryGroups.Find(id);

			if (group == null)
			{
				return HttpNotFound();
			}

			return View(group);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id = 0)
		{
			CategoryGroup group = db.CategoryGroups.Find(id);

			if (group == null)
			{
				return HttpNotFound();
			}

			db.CategoryGroups.Remove(group);
			db.SaveChanges();

			return RedirectToAction("Index", "Home");
		}
	}
}

Spending/Views/CategoryGroups/Create.cshtml
@model CategoryGroup

@{
    ViewBag.Title = "Create";
}

@section head
{
	<style type="text/css">
		th
		{
		    text-align: left;
		    padding-right: 10px;
		}
		th, td
		{
		    padding-top: 5px;
		    padding-bottom: 5px;
		}
	</style>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

	<table>
		<tr>
			<th>@Html.LabelFor(model => model.Name)</th>
			<td>
				@Html.EditorFor(model => model.Name)
				@Html.ValidationMessageFor(model => model.Name)
			</td>
		</tr>
	</table>
	
    <p>
		<input type="submit" value="Create" />
		@Html.ActionLink("Cancel", "Index", "Home")
    </p>
}

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Spending/Views/CategoryGroups/Edit.cshtml
@model CategoryGroup

@{
    ViewBag.Title = "Edit";
}

@section head
{
	<style type="text/css">
		th
		{
		    text-align: left;
		    padding-right: 10px;
		}
		th, td
		{
		    padding-top: 5px;
		    padding-bottom: 5px;
		}
	</style>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.Id)

	<table>
		<tr>
			<th>@Html.LabelFor(model => model.Name)</th>
			<td>
				@Html.EditorFor(model => model.Name)
				@Html.ValidationMessageFor(model => model.Name)
			</td>
		</tr>
	</table>
		
	<p>
        <input type="submit" value="Save" />
		@Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "cancelLink" })
    </p>
}

@using (Html.BeginForm("Delete", "CategoryGroups", new { id = Model.Id }))
{
	<input type="submit" value="Delete" />
}

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}